export const GET_POKEMON = 'GET_POKEMON'
export const GET_POKEMON_INFO = 'GET_POKEMON_INFO'
export const FAILD_POKEMON_INFO = 'FAILD_POKEMON_INFO'
export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST'
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS'
export const GET_POKEMON_INFO_SUCCESS = 'GET_POKEMON_INFO_SUCCESS'
export const SELECT_POKEMON = 'SELECT_POKEMON'
export const NEXT_POKEMON = 'NEXT_POKEMON'

